### ISSUE TITLE
problem with autocomplete

### ISSUE THREAD

**Issue by abalest14** [Faryshta/yii2-jquery-tagsinput#1]
Good morning, i am trying to use the autocomplete function with this code:
`$form->field($model, 'tipo')->widget(JqueryTagsInput::className(),[
    'clientOptions' => [
        'defaultText' => 'aggiungi',
        'width'       => '100%',
        'allowDuplicates' => false,
        'autocomplete_url' => 'tipiSearch.php',
    ]
])`

the php file return a json encoded like this ["Amministrativo","Commerciale","Tecnico"] but dosen't work.
thanks

**Comment by Faryshta** [comment]
which part doesn't work?

Does the ajax gets executed in the debug console?

Do you have pretty url's? The `'tipiSearch.php` format sounds very vague specially when working in yii2

**Comment by abalest14** [comment]
in attach a screen of the error. in this module i have two taginput field
tipo contatto e provenienza, when i add the autocomplete parameter, the
taginput disappear from the provenienza field.
the tipiSearch.php return this parameter:
["Amministrativo","Commerciale","Tecnico"]
thanks for help

2016-05-06 21:23 GMT+02:00 Angel Guevara notifications@github.com:

**Comment by Faryshta** [comment]
@abalest14 on githu issues I can't see any file you have attached by email, you have to upload here on github directly.

**Comment by abalest14** [comment]
i have upload the screenshot. thanks

**Comment by abalest14** [comment]
i have resolved, was missing the jquery ui extension, i have installed it
and now work like a sharm. thanks

2016-05-08 21:07 GMT+02:00 Angel Guevara notifications@github.com:

**Comment by Faryshta** [comment]
@abalest14 ohh cool, let me add that to the docs then for future reference before closing this issue

**Comment by Faryshta** [comment]
@abalest14 how about if the widget checks if `options['ajaxurl']` is set, if it is, then it will load the jquery ui asset.
